export { default as Navigation } from './Navigation'
export { default as Hero } from './Hero'
export { default as About } from './About'
export { default as Expertise } from './Expertise'
export { default as Projects } from './Projects'
export { default as Contact } from './Contact'
export { default as Footer } from './Footer'
export { default as InteractiveAvatar } from './InteractiveAvatar'
